# -*- coding: utf-8 -*-
"""cs01-17ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUjZKdCp5CiToIw47amkOAmN3rsKtyXU
"""

from numpy import random

x = random.randint(101, size=(5,10))

print(x)

import numpy as np
arr = np.array([3,2,0,1])

print(np.sort(x))